### ISSUE TITLE
add support for .refactorlog

### ISSUE THREAD

**Issue by knoxi** [rr-wfm/MSBuild.Sdk.SqlProj#45]
I'm migrating our builds to linux based container builds.
I tried out to add an additional project as mentioned in [this blog](https://erikej.github.io/efcore/2020/05/11/ssdt-dacpac-netcore.html).
Comparing the output, I noticed that the `refactor.xml` is missing in the dacpac, which is based on the `[ProjectName].refactorlog` file.

Is this already supported? Do I have to reference the refactorlog file in the project file somehow like the Pre- and post deployment scripts?

**Comment by jmezach** [comment]
@knoxi That's a great question actually. I'm not sure how this works exactly with the existing SSDT projects. Could you share an example of the `.refactorlog` file and the resulting `refactor.xml` file in the dacpac? That might give us some pointers as to what has to happen to make this work.

**Comment by jeffrosenberg** [comment]
I think that, similar to how the `<PostDeploy />` element is handled, you'd want to take the path of a `<RefactorLog />` element and use it to set [`PackageOptions.RefactorLogPath`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.packageoptions.refactorlogpath?view=sql-dacfx-150).

**Comment by jmezach** [comment]
That looks easy enough to add. But I think the `.refactorlog` file will only be modified when you make changes to the original `.sqlproj`. That won't be a problem for people using the "companion" project approach I guess, but for those that use the `.csproj` exclusively that wouldn't work so we''l have to make that abundantly clear in the documentation ;).

**Comment by knoxi** [comment]
Regarding the two files, it looks that easy as @jeffrosenberg mentioned above.
[refactorlog.zip](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/files/5157144/refactorlog.zip)

We actually have only solutions with "companion" project approaches, so it would be really great to get this support.Of course this should be clear in the docs for the `.csproj` usages.
So then we can expect a fast update ;-) ?

**Comment by jmezach** [comment]
Quickest way would probably be submitting a PR. I don't think I'll have time to implement this soon.

**Comment by knoxi** [comment]
I created a PR for supporting .refactorlog

I couldn't test the changed `SDK.targets`, for the Dacpac tool implementation I have added unit tests.

**Comment by jmezach** [comment]
I've just released v1.5.0 with support for this. Thanks to @knoxi for his work on this.

For some reason the new template pack got released as a beta. Something went wrong during CI which I'll need to figure out.

**Comment by PontiusTheBarbarian** [comment]
> That looks easy enough to add. But I think the `.refactorlog` file will only be modified when you make changes to the original `.sqlproj`. That won't be a problem for people using the "companion" project approach I guess, but for those that use the `.csproj` exclusively that wouldn't work so we''l have to make that abundantly clear in the documentation ;).

Did you get round to updating the documentation on this? Is standalone still not supported?
